
CREATE TABLE [dbo].[Books](
	[Inventar_Number] [nvarchar](16) NOT NULL,
	[ISBN] [varchar](13) NOT NULL,
	[Title] [nvarchar](255) NOT NULL,
	[Author] [nvarchar](255) NOT NULL,
	[Desription] [nvarchar](255) NULL,
	[Condition] [nvarchar](100) NULL,
	[Publisher] [nvarchar](max) NULL,
 CONSTRAINT [CPK_Books] PRIMARY KEY CLUSTERED 
(
	[Inventar_Number] ASC,
	[ISBN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[ISBN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Inventar_Number] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Issues]    Script Date: 04.10.2020 12:24:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Issues](
	[IssueID] [int] IDENTITY(1,1) NOT NULL,
	[FK_ISBN] [varchar](13) NOT NULL,
	[FK_Inventar_Number] [nvarchar](16) NOT NULL,
	[FK_UserID] [int] NOT NULL,
	[FK_MANumber] [int] NOT NULL,
	[ReturnDate] [date] NOT NULL,
	[StartDate] [date] NOT NULL,
	[IssueState] [char](3) NOT NULL,
 CONSTRAINT [CPK_IssuesID] PRIMARY KEY CLUSTERED 
(
	[IssueID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[IssueID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Reservations]    Script Date: 04.10.2020 12:24:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Reservations](
	[ReservationsID] [int] IDENTITY(1,1) NOT NULL,
	[FK_ISBN] [varchar](13) NOT NULL,
	[FK_Inventar_Number] [nvarchar](16) NOT NULL,
	[FK_UserID] [int] NOT NULL,
	[FK_MANumber] [int] NOT NULL,
	[ReservationDate] [date] NULL,
 CONSTRAINT [CPK_ReservationsID] PRIMARY KEY CLUSTERED 
(
	[ReservationsID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[ReservationsID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 04.10.2020 12:24:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[UserID] [int] IDENTITY(1,1) NOT NULL,
	[LastName] [nvarchar](255) NOT NULL,
	[FirstName] [nvarchar](255) NOT NULL,
	[EMailAddress] [nvarchar](255) NOT NULL,
	[MANumber] [int] NOT NULL,
	[Rolle] [char](3) NOT NULL,
	[EncryptedPW] [nvarchar](max) NULL,
 CONSTRAINT [CPK_Users] PRIMARY KEY CLUSTERED 
(
	[UserID] ASC,
	[MANumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[MANumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[Issues] ADD  DEFAULT ('0000000000000') FOR [FK_ISBN]
GO
ALTER TABLE [dbo].[Issues] ADD  DEFAULT ('0000000000000000') FOR [FK_Inventar_Number]
GO
ALTER TABLE [dbo].[Issues] ADD  DEFAULT ((0)) FOR [FK_UserID]
GO
ALTER TABLE [dbo].[Issues] ADD  DEFAULT ((0)) FOR [FK_MANumber]
GO
ALTER TABLE [dbo].[Users] ADD  DEFAULT ('ben') FOR [Rolle]
GO
ALTER TABLE [dbo].[Issues]  WITH CHECK ADD  CONSTRAINT [CFK_Inventar_NumberIssues] FOREIGN KEY([FK_Inventar_Number])
REFERENCES [dbo].[Books] ([Inventar_Number])
GO
ALTER TABLE [dbo].[Issues] CHECK CONSTRAINT [CFK_Inventar_NumberIssues]
GO
ALTER TABLE [dbo].[Issues]  WITH CHECK ADD  CONSTRAINT [CFK_ISBNIssues] FOREIGN KEY([FK_ISBN])
REFERENCES [dbo].[Books] ([ISBN])
ON DELETE SET DEFAULT
GO
ALTER TABLE [dbo].[Issues] CHECK CONSTRAINT [CFK_ISBNIssues]
GO
ALTER TABLE [dbo].[Issues]  WITH CHECK ADD  CONSTRAINT [CFK_MANumberIssues] FOREIGN KEY([FK_MANumber])
REFERENCES [dbo].[Users] ([MANumber])
ON DELETE SET DEFAULT
GO
ALTER TABLE [dbo].[Issues] CHECK CONSTRAINT [CFK_MANumberIssues]
GO
ALTER TABLE [dbo].[Issues]  WITH CHECK ADD  CONSTRAINT [CFK_UserIDIssues] FOREIGN KEY([FK_UserID])
REFERENCES [dbo].[Users] ([UserID])
GO
ALTER TABLE [dbo].[Issues] CHECK CONSTRAINT [CFK_UserIDIssues]
GO
ALTER TABLE [dbo].[Reservations]  WITH CHECK ADD  CONSTRAINT [CFK_Inventar_NumberReservations] FOREIGN KEY([FK_Inventar_Number])
REFERENCES [dbo].[Books] ([Inventar_Number])
GO
ALTER TABLE [dbo].[Reservations] CHECK CONSTRAINT [CFK_Inventar_NumberReservations]
GO
ALTER TABLE [dbo].[Reservations]  WITH CHECK ADD  CONSTRAINT [CFK_ISBNReservations] FOREIGN KEY([FK_ISBN])
REFERENCES [dbo].[Books] ([ISBN])
GO
ALTER TABLE [dbo].[Reservations] CHECK CONSTRAINT [CFK_ISBNReservations]
GO
ALTER TABLE [dbo].[Reservations]  WITH CHECK ADD  CONSTRAINT [CFK_MANumberReservations] FOREIGN KEY([FK_MANumber])
REFERENCES [dbo].[Users] ([MANumber])
GO
ALTER TABLE [dbo].[Reservations] CHECK CONSTRAINT [CFK_MANumberReservations]
GO
ALTER TABLE [dbo].[Reservations]  WITH CHECK ADD  CONSTRAINT [CFK_UserIDReservations] FOREIGN KEY([FK_UserID])
REFERENCES [dbo].[Users] ([UserID])
GO
ALTER TABLE [dbo].[Reservations] CHECK CONSTRAINT [CFK_UserIDReservations]
GO
