//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservations
    {
        public int ReservationsID { get; set; }
        public string FK_ISBN { get; set; }
        public string FK_Inventar_Number { get; set; }
        public int FK_UserID { get; set; }
        public int FK_MANumber { get; set; }
        public Nullable<System.DateTime> ReservationDate { get; set; }
    }
}
